name: Ansible lint

 'on':
  pull_request:
  push:
    branches:
      - master

  jobs:
   build:

      runs-on: ubuntu-latest
  
      steps:
     - uses: actions/checkout@v2
     - name: Set up Python 
       uses: actions/setup-python@v1
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install ansible ansible-lint
     - name: Lint playbook
       run: |
         ansible-playbook site.yml --syntax-check
         ansible-lint site.yml
